### ISSUE TITLE
[BUG] ContextMenu Provider throws Error

### ISSUE THREAD

**Issue by YannikSMYLIE** [TYPO3-Solr/ext-tika#101]
If I open a ContextMenu from a page or item, the Provider from Tika (ApacheSolrForTypo3\Tika\ContextMenu\Preview) tries to check if it can handle the context menu or not.
If there is no file with the same uid as the page or content element, the Provider will throw an error, for example:
#1317178604: No file found for given UID: 120 (More information)

So Tika is blocking you from using the ContextMenu at Pages and Content Elements (maybe more).
Checked on TYPO3 8.7.17/18

**Comment by timohund** [comment]
@YannikSMYLIE this is fixed in dev-master, can you test that? Will be part of 3.1.1

**Comment by YannikSMYLIE** [comment]
Still throws Error in my case. Also I had problems with the ContextMenu of Records.
This thing here seems not to work:

```
if ($this->table !== 'sys_file') {
   return false;
}
```

$this -> table is "tt_content", nevertheless the function is not returning false.
